server:
  port: 9966
  tomcat:
    threads:
      max: 400
      min-spare: 400

spring:
  application:
    name: sharding-demo
  datasource:
    druid:
      filters: stat,wall
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/order0
      username: root
      password: 123456
      initialSize: 40
      maxActive: 40
      minIdle: 40
      max-wait: 10000


mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  # 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.joseph.sharding.demo.entity
  configuration:
    # 不开启二级缓存
    cache-enabled: false
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

